// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingBots.Native.Infra.DbAccess;

#nullable disable

namespace TradingBots.Native.Infra.DbAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250527124816_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TradingBots.CrossCutters.Models.CompletedDealBase", b =>
                {
                    b.Property<string>("CompletedDealID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("AccountBalance_StarOfTrading")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Amount_CurrencySymbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Amount_Total_Calibrated")
                        .HasColumnType("decimal(24,8)");

                    b.Property<decimal>("Amount_Total_Organic")
                        .HasColumnType("decimal(24,8)");

                    b.Property<string>("ApiOrderID_DealClose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ApiOrderID_DealOpen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BotID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BotInstanceID")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("BotSetUp_InstanceGap_Absolute")
                        .HasColumnType("decimal(24,8)");

                    b.Property<decimal>("BotSetUp_InstanceGap_Trading")
                        .HasColumnType("decimal(24,8)");

                    b.Property<decimal>("BotSetUp_StopLoss_EventualTradePrice")
                        .HasColumnType("decimal(24,8)");

                    b.Property<decimal>("BotSetUp_StopLoss_TriggerChangeAmount")
                        .HasColumnType("decimal(24,8)");

                    b.Property<decimal>("BotSetUp_StopOrder_Trigger_Price")
                        .HasColumnType("decimal(24,8)");

                    b.Property<decimal>("BotSetUp_TPCondition")
                        .HasColumnType("decimal(24,8)");

                    b.Property<decimal>("BotSetUp_TTP_ActivationPoint_OffsetPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("BotSetUp_TTP_Active")
                        .HasColumnType("bit");

                    b.Property<decimal>("BotSetUp_TTP_EventualTrade_OffsetPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BotSetUp_TTP_TradeTriggerPoint_OffsetPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BotSetUp_TradeDirection")
                        .HasColumnType("int");

                    b.Property<int>("BotSetUp_TradeTimeSpan")
                        .HasColumnType("int");

                    b.Property<string>("BotSetUp_TradingPair")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("CalibrationFactor")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ChangeFraction_Calibrated")
                        .HasColumnType("decimal(12,4)");

                    b.Property<decimal>("ChangeFraction_Organic")
                        .HasColumnType("decimal(12,4)");

                    b.Property<DateTime>("DateTime_Completed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTime_Started")
                        .HasColumnType("datetime2");

                    b.Property<int>("DbID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DbID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DbID"));

                    b.Property<int>("DealClose_Method")
                        .HasColumnType("int");

                    b.Property<decimal>("DealClose_Price")
                        .HasColumnType("decimal(24,8)");

                    b.Property<string>("DealID")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("DealOpen_Price")
                        .HasColumnType("decimal(24,8)");

                    b.Property<int>("Instance_Priority")
                        .HasColumnType("int");

                    b.Property<decimal>("Instance_TTP_EventualTrade_Price")
                        .HasColumnType("decimal(24,8)");

                    b.Property<decimal>("Instance_TTP_Extra_Fraction")
                        .HasColumnType("decimal(14,6)");

                    b.Property<decimal>("ProfitAmount_DCA")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("ProfitAmount_FractionOfTotal_DCA")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("ProfitAmount_FractionOfTotal_SingleDeal")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("ProfitAmount_SingleDeal")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("ROC_Account_DCA_Fraction")
                        .HasColumnType("decimal(14,6)");

                    b.Property<decimal>("ROC_Account_SingleDeal_Fraction")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("ROC_Bot_DCA_Fraction")
                        .HasColumnType("decimal(14,6)");

                    b.Property<decimal>("ROC_Bot_SingleDeal_Fraction")
                        .HasColumnType("decimal(14,6)");

                    b.Property<decimal>("ROC_Instance_DCA_Fraction")
                        .HasColumnType("decimal(14,6)");

                    b.Property<decimal>("ROC_Instance_SingleDeal_Fraction")
                        .HasColumnType("decimal(14,6)");

                    b.Property<decimal>("TimeToComplete_Seconds")
                        .HasColumnType("decimal(10,0)");

                    b.Property<long>("TimeToComplete_TimeSpan")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TradingFees_To_ProfitAmount_DCA")
                        .HasColumnType("decimal(14,6)");

                    b.Property<decimal>("TradingFees_To_ProfitAmount_SingleDeal")
                        .HasColumnType("decimal(14,6)");

                    b.Property<decimal>("TradingFees_Total")
                        .HasColumnType("decimal(24,8)");

                    b.Property<decimal>("Volume_Calibrated")
                        .HasColumnType("decimal(24,8)");

                    b.Property<decimal>("Volume_Organic")
                        .HasColumnType("decimal(24,8)");

                    b.Property<int>("__CompletedDeal_Type")
                        .HasColumnType("int");

                    b.HasKey("CompletedDealID");

                    b.ToTable("CompletedDeal", "logic");

                    b.HasDiscriminator<int>("__CompletedDeal_Type").HasValue(0);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TradingBots.Native.Domain.Bot", b =>
                {
                    b.Property<string>("BotID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<decimal>("BaseDealOpenPrice")
                        .HasColumnType("decimal(24,8)");

                    b.Property<decimal>("Budget_TotalForBot")
                        .HasColumnType("decimal(24,8)")
                        .HasColumnName("Budget");

                    b.Property<int>("CstAve_Method")
                        .HasColumnType("int");

                    b.Property<int>("CstAve_Rndng_PositionAmount")
                        .HasColumnType("int");

                    b.Property<int>("CstAve_Rndng_Volume")
                        .HasColumnType("int");

                    b.Property<decimal>("CstAve_ScalingAmount")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("DbID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DbID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DbID"));

                    b.Property<int>("DealClose_MinRank_RelToMarket")
                        .HasColumnType("int");

                    b.Property<decimal>("DealClose_OffsetPercentToMarket")
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("DealClose_TakeProfit_Percent_Default")
                        .HasColumnType("decimal(9,4)")
                        .HasColumnName("TakeProfit_DealClose");

                    b.Property<decimal>("DealOpen_InstanceGap_Percent_Default")
                        .HasColumnType("decimal(9,4)")
                        .HasColumnName("InstanceGap_DealOpen");

                    b.Property<int>("DealOpen_MinRank_RelToPriceLimit")
                        .HasColumnType("int");

                    b.Property<decimal>("DealOpen_OffsetPercentToMarket")
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("DealOpen_PriceLimit_Default")
                        .HasColumnType("decimal(24,8)")
                        .HasColumnName("PriceLimit_DealOpen");

                    b.Property<bool>("DealsTracking_Active")
                        .HasColumnType("bit");

                    b.Property<bool>("DelayedOrderTrigger_Active")
                        .HasColumnType("bit");

                    b.Property<int>("DelayedOrderTrigger_ImmediateOrdersCount")
                        .HasColumnType("int");

                    b.Property<decimal>("DelayedOrderTrigger_PercentRange")
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("Leverage_Factor")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("MarketCategory")
                        .HasColumnType("int");

                    b.Property<int>("OrderExecution_DealClose")
                        .HasColumnType("int");

                    b.Property<int>("OrderExecution_DealOpen")
                        .HasColumnType("int");

                    b.Property<int>("OrderTrigger_DealClose")
                        .HasColumnType("int");

                    b.Property<int>("OrderTrigger_DealOpen")
                        .HasColumnType("int");

                    b.Property<int>("PartialTP_RemainderAllocation")
                        .HasColumnType("int");

                    b.Property<int>("PartialTP_Volume_Rounding")
                        .HasColumnType("int");

                    b.Property<int>("PosTracking_DealClose_OffSetMethod")
                        .HasColumnType("int")
                        .HasColumnName("DealClose_OffSetMethod");

                    b.Property<decimal>("PosTracking_DealClose_Price_MinOffSetPercent")
                        .HasColumnType("decimal(8,4)")
                        .HasColumnName("DealClose_Price_MinOffSetPercent");

                    b.Property<decimal>("PosTracking_DealClose_TotalPosSize_Min_Calibrated")
                        .HasColumnType("decimal(24,8)")
                        .HasColumnName("DealClose_TotalPosSize_Min_Calibrated");

                    b.Property<bool>("PosTracking_DealOpen_Active")
                        .HasColumnType("bit")
                        .HasColumnName("DealOpen_Active");

                    b.Property<decimal>("PosTracking_DealOpen_Price_MinOffSetPercent")
                        .HasColumnType("decimal(8,4)")
                        .HasColumnName("DealOpen_Price_MinOffSetPercent");

                    b.Property<decimal>("PosTracking_DealOpen_TotalPosSize_Max_Calibrated")
                        .HasColumnType("decimal(24,8)")
                        .HasColumnName("DealOpen_TotalPosSize_Max_Calibrated");

                    b.Property<int>("ProfitReInvestment_Type")
                        .HasColumnType("int");

                    b.Property<decimal>("ProfitReinvestment_Percent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("QuoteCurrencyAsProductID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TradeDirection")
                        .HasColumnType("int");

                    b.Property<string>("TradeExchange")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TradeExchangeConfigurationID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TradeTimeSpan")
                        .HasColumnType("int");

                    b.Property<decimal>("TradingFee_Percent")
                        .HasColumnType("decimal(6,4)");

                    b.Property<string>("TradingPair")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Volume_BatchUnits")
                        .HasColumnType("int");

                    b.HasKey("BotID");

                    b.ToTable("Bot_01_Main", "logic");

                    b.SplitToTable("Bot_02_DynamicBehaviour", "logic", t =>
                        {
                            t.Property("DealClose_OffsetPercentToMarket");

                            t.Property("DealOpen_MinRank_RelToPriceLimit")
                                .HasColumnName("MinRank_DealOpen");

                            t.Property("DealOpen_OffsetPercentToMarket");

                            t.Property("OrderExecution_DealClose");

                            t.Property("OrderExecution_DealOpen");

                            t.Property("OrderTrigger_DealClose");

                            t.Property("OrderTrigger_DealOpen");

                            t.Property("TradeDirection");
                        });

                    b.SplitToTable("Bot_03_PosSizeTracking", "logic", t =>
                        {
                            t.Property("PosTracking_DealClose_OffSetMethod");

                            t.Property("PosTracking_DealClose_Price_MinOffSetPercent");

                            t.Property("PosTracking_DealClose_TotalPosSize_Min_Calibrated");

                            t.Property("PosTracking_DealOpen_Active");

                            t.Property("PosTracking_DealOpen_Price_MinOffSetPercent");

                            t.Property("PosTracking_DealOpen_TotalPosSize_Max_Calibrated");
                        });

                    b.SplitToTable("Bot_04_CostAveraging", "logic", t =>
                        {
                            t.Property("CstAve_Method")
                                .HasColumnName("Method");

                            t.Property("CstAve_Rndng_PositionAmount")
                                .HasColumnName("Rndng_PositionAmount");

                            t.Property("CstAve_Rndng_Volume")
                                .HasColumnName("Rndng_Volume");

                            t.Property("CstAve_ScalingAmount")
                                .HasColumnName("ScalingAmount");
                        });

                    b.SplitToTable("Bot_05_Profit", "logic", t =>
                        {
                            t.Property("DealsTracking_Active")
                                .HasColumnName("DealsTracking_Active");

                            t.Property("Leverage_Factor")
                                .HasColumnName("Leverage_Factor");

                            t.Property("MarketCategory")
                                .HasColumnName("MarketCategory");

                            t.Property("PartialTP_RemainderAllocation")
                                .HasColumnName("PartialTP_RemainderAllocation");

                            t.Property("PartialTP_Volume_Rounding")
                                .HasColumnName("PartialTP_Volume_Rounding");

                            t.Property("ProfitReInvestment_Type")
                                .HasColumnName("ProfitReInvestment_Type");

                            t.Property("ProfitReinvestment_Percent")
                                .HasColumnName("ProfitReinvestment_Percent");
                        });

                    b.SplitToTable("Bot_06_Others", "logic", t =>
                        {
                            t.Property("BaseDealOpenPrice")
                                .HasColumnName("BaseDealOpenPrice");

                            t.Property("DealClose_MinRank_RelToMarket")
                                .HasColumnName("DealClose_MinRank_RelToMarket");

                            t.Property("DelayedOrderTrigger_Active")
                                .HasColumnName("DelayedOrderTrigger_Active");

                            t.Property("DelayedOrderTrigger_ImmediateOrdersCount")
                                .HasColumnName("DelayedOrderTrigger_ImmediateOrdersCount");

                            t.Property("DelayedOrderTrigger_PercentRange")
                                .HasColumnName("DelayedOrderTrigger_PercentRange");

                            t.Property("QuoteCurrencyAsProductID")
                                .HasColumnName("QuoteCurrencyAsProductID");

                            t.Property("TradeTimeSpan")
                                .HasColumnName("TradeTimeSpan");
                        });

                    b.SplitToTable("Bot_07_ExchangeConfig", "logic", t =>
                        {
                            t.Property("TradeExchange");

                            t.Property("TradeExchangeConfigurationID");

                            t.Property("TradingFee_Percent");

                            t.Property("Volume_BatchUnits");
                        });
                });

            modelBuilder.Entity("TradingBots.Native.Domain.BotInstance", b =>
                {
                    b.Property<string>("BotInstanceID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("BotID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(24,8)");

                    b.Property<string>("BudgetAllocationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("BudgetPercentageOfParent")
                        .HasColumnType("decimal(9,4)");

                    b.Property<int>("DbID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DbID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DbID"));

                    b.Property<decimal>("DealOpen_FeeAmount")
                        .HasColumnType("decimal(24,8)");

                    b.Property<decimal>("DealOpen_Price_Final")
                        .HasColumnType("decimal(24,8)");

                    b.Property<decimal>("DealOpen_Price_Initial")
                        .HasColumnType("decimal(24,8)");

                    b.Property<decimal>("InstanceGap_Percent")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("InstanceGap_Reference")
                        .HasColumnType("int");

                    b.Property<decimal>("OrderVolume_Calibrated")
                        .HasColumnType("decimal(24,8)");

                    b.Property<decimal>("OrderVolume_Organic")
                        .HasColumnType("decimal(24,8)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("BotInstanceID");

                    b.HasIndex("BotID");

                    b.ToTable("BotInstance", "logic");
                });

            modelBuilder.Entity("TradingBots.Native.Domain.BotInstanceState", b =>
                {
                    b.Property<string>("BotInstanceStateID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("ApiOrderID_Current")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ApiOrderID_DealClose")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ApiOrderID_DealOpen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ApiTimeStamp_Current")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ApiTimeStamp_DealClose")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ApiTimeStamp_DealOpen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BotInstanceID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CurrentState")
                        .HasColumnType("int");

                    b.Property<int>("DbID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DbID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DbID"));

                    b.Property<string>("DealID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PrevState")
                        .HasColumnType("int");

                    b.Property<int>("TradeWorkflowStatus")
                        .HasColumnType("int");

                    b.HasKey("BotInstanceStateID");

                    b.HasIndex("BotInstanceID")
                        .IsUnique();

                    b.ToTable("BotInstanceState", "logic");
                });

            modelBuilder.Entity("TradingBots.Native.Domain.BotPartialTP", b =>
                {
                    b.Property<string>("BotPartialTPID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("ApiOrderID_Current")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ApiOrderID_DealClose")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ApiOrderID_DealOpen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ApiTimeStamp_Current")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ApiTimeStamp_DealClose")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ApiTimeStamp_DealOpen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BotInstanceID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CurrentState")
                        .HasColumnType("int");

                    b.Property<int>("DbID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DbID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DbID"));

                    b.Property<decimal>("DealClose_OffsetPercentToMarket")
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("DealClose_Price_Final")
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("DealClose_Price_Initial")
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("DealClose_Price_Initial_Relevant")
                        .HasColumnType("decimal(9,4)");

                    b.Property<string>("DealID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrderExecution_DealClose")
                        .HasColumnType("int");

                    b.Property<int>("OrderTrigger_DealClose")
                        .HasColumnType("int");

                    b.Property<int>("PartialTpStatus")
                        .HasColumnType("int");

                    b.Property<int>("PosTracking_DealClose_OffSetMethod")
                        .HasColumnType("int");

                    b.Property<decimal>("PosTracking_DealClose_Price_MinOffSetPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PrevState")
                        .HasColumnType("int");

                    b.Property<int>("Priority_Instance")
                        .HasColumnType("int");

                    b.Property<int>("Priority_Partial")
                        .HasColumnType("int");

                    b.Property<decimal>("Profit_EstAmount")
                        .HasColumnType("decimal(9,4)");

                    b.Property<int>("ReferencePoint_Type")
                        .HasColumnType("int");

                    b.Property<decimal>("TTP_ActivationPoint_OffSetPercent")
                        .HasColumnType("decimal(9,4)");

                    b.Property<bool>("TTP_Active")
                        .HasColumnType("bit");

                    b.Property<int>("TTP_Attempts_Current")
                        .HasColumnType("int");

                    b.Property<int>("TTP_Attempts_Max")
                        .HasColumnType("int");

                    b.Property<decimal>("TTP_EventualPrice_DealClose")
                        .HasColumnType("decimal(24,8)");

                    b.Property<decimal>("TTP_EventualPrice_Trigger")
                        .HasColumnType("decimal(24,8)");

                    b.Property<decimal>("TTP_OrderPoint_OffSetPercent")
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("TTP_TriggerPoint_OffSetPercent")
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("TakeProfit_Percent")
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("Volume_ActualClosed")
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("Volume_CalcParameter_Percent")
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("Volume_CalcResult_Amount")
                        .HasColumnType("decimal(24,8)");

                    b.HasKey("BotPartialTPID");

                    b.HasIndex("BotInstanceID");

                    b.ToTable("BotPartialTP_00_Root", "logic");

                    b.SplitToTable("BotPartialTP_01_Main", "logic", t =>
                        {
                            t.Property("Active");

                            t.Property("DealClose_OffsetPercentToMarket");

                            t.Property("OrderExecution_DealClose");

                            t.Property("OrderTrigger_DealClose");

                            t.Property("Priority_Instance");

                            t.Property("Priority_Partial");

                            t.Property("ReferencePoint_Type");

                            t.Property("TakeProfit_Percent");

                            t.Property("Volume_CalcParameter_Percent");

                            t.Property("Volume_CalcResult_Amount");
                        });

                    b.SplitToTable("BotPartialTP_02_TrlngTP", "logic", t =>
                        {
                            t.Property("Priority_Instance");

                            t.Property("Priority_Partial");

                            t.Property("TTP_ActivationPoint_OffSetPercent")
                                .HasColumnName("ActivationPoint_OffSetPercent");

                            t.Property("TTP_Active")
                                .HasColumnName("Active");

                            t.Property("TTP_Attempts_Current")
                                .HasColumnName("Attempts_Current");

                            t.Property("TTP_Attempts_Max")
                                .HasColumnName("Attempts_Max");

                            t.Property("TTP_EventualPrice_DealClose")
                                .HasColumnName("EventualPrice_DealClose");

                            t.Property("TTP_EventualPrice_Trigger")
                                .HasColumnName("EventualPrice_Trigger");

                            t.Property("TTP_OrderPoint_OffSetPercent")
                                .HasColumnName("OrderPoint_OffSetPercent");

                            t.Property("TTP_TriggerPoint_OffSetPercent")
                                .HasColumnName("TriggerPoint_OffSetPercent");
                        });

                    b.SplitToTable("BotPartialTP_03_State", "logic", t =>
                        {
                            t.Property("ApiOrderID_Current");

                            t.Property("ApiOrderID_DealClose");

                            t.Property("ApiOrderID_DealOpen");

                            t.Property("ApiTimeStamp_Current");

                            t.Property("ApiTimeStamp_DealClose");

                            t.Property("ApiTimeStamp_DealOpen");

                            t.Property("CurrentState");

                            t.Property("DealClose_Price_Final");

                            t.Property("DealClose_Price_Initial");

                            t.Property("DealClose_Price_Initial_Relevant");

                            t.Property("DealID");

                            t.Property("PartialTpStatus");

                            t.Property("PrevState");

                            t.Property("Priority_Instance");

                            t.Property("Priority_Partial");

                            t.Property("Profit_EstAmount");

                            t.Property("Volume_ActualClosed");
                        });

                    b.SplitToTable("BotPartialTP_04_PosSizeTrck", "logic", t =>
                        {
                            t.Property("PosTracking_DealClose_OffSetMethod")
                                .HasColumnName("DealClose_OffSetMethod");

                            t.Property("PosTracking_DealClose_Price_MinOffSetPercent")
                                .HasColumnName("DealClose_Price_MinOffSetPercent");

                            t.Property("Priority_Instance");

                            t.Property("Priority_Partial");
                        });
                });

            modelBuilder.Entity("TradingBots.Native.Domain.GlobalStopLoss", b =>
                {
                    b.Property<string>("GlobalStopLossID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ActivationPoint_OffSetPercent")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("Activation_CalculatedPrice")
                        .HasColumnType("decimal(24,8)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("ApiOrderID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ApiTimeStamp_Current")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ApiTimeStamp_DealClose")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ApiTimeStamp_DealOpen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BotID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("CircuitBreaker_Active")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CircuitBreaker_TimeOut_EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CircuitBreaker_TimeOut_Seconds")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CircuitBreaker_TimeOut_StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DbID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DbID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DbID"));

                    b.Property<string>("DealID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NumberOfRuns_Current")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfRuns_Max")
                        .HasColumnType("int");

                    b.Property<decimal>("PositionAmount_Percent")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("PositionAmount_Reserved")
                        .HasColumnType("decimal(24,8)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("StopLossReference")
                        .HasColumnType("int");

                    b.Property<int>("StopLossType")
                        .HasColumnType("int");

                    b.Property<decimal>("TakeLossPoint_OffSetPercent")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("TakeLoss_CalculatedPrice")
                        .HasColumnType("decimal(24,8)");

                    b.Property<decimal>("TakeLoss_FinalPrice")
                        .HasColumnType("decimal(24,8)");

                    b.Property<decimal>("Volume_Calculated")
                        .HasColumnType("decimal(24,8)");

                    b.Property<int>("WorkflowStatus")
                        .HasColumnType("int");

                    b.HasKey("GlobalStopLossID");

                    b.HasIndex("BotID");

                    b.ToTable("GlobalStopLoss", "logic");
                });

            modelBuilder.Entity("TradingBots.Native.Domain.ReOrdersCategory", b =>
                {
                    b.Property<string>("ReOrdersCategoryID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("AmountOfPosition_Estimate")
                        .HasColumnType("decimal(24,8)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("DbID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DbID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DbID"));

                    b.Property<decimal>("DealClose_SpecificStartPrice")
                        .HasColumnType("decimal(24,8)");

                    b.Property<decimal>("DealClose_StartOffSet")
                        .HasColumnType("decimal(10,4)");

                    b.Property<bool>("DoPlaceOrders")
                        .HasColumnType("bit");

                    b.Property<int>("NumberOfOrders")
                        .HasColumnType("int");

                    b.Property<decimal>("OrdersGap_Percent")
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("OverallPriority")
                        .HasColumnType("int");

                    b.Property<int>("PriceReference")
                        .HasColumnType("int");

                    b.HasKey("ReOrdersCategoryID");

                    b.ToTable("ReOrdersCategory", "logic");
                });

            modelBuilder.Entity("TradingBots.Native.Domain.ReOrdersMain", b =>
                {
                    b.Property<string>("ReOrdersMainID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DbID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DbID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DbID"));

                    b.Property<decimal>("PositionLimit")
                        .HasColumnType("decimal(24,8)");

                    b.HasKey("ReOrdersMainID");

                    b.ToTable("ReOrdersMain", "logic");
                });

            modelBuilder.Entity("TradingBots.Native.Domain.RecommendationAction", b =>
                {
                    b.Property<string>("RecommendationActionID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DbID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DbID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DbID"));

                    b.Property<DateTime>("DealClose_ActTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DealClose_RecomTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DealID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DealOpen_ActTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DealOpen_RecomTime")
                        .HasColumnType("datetime2");

                    b.HasKey("RecommendationActionID");

                    b.ToTable("RecommendationAction", "logic");
                });

            modelBuilder.Entity("TradingBots.Native.Domain.RecommendationFilter", b =>
                {
                    b.Property<string>("RecommendationFilterID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("AttributeToFilter")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<int>("DbID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DbID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DbID"));

                    b.Property<int>("DealActionType")
                        .HasColumnType("int");

                    b.Property<int>("MarketCategory")
                        .HasColumnType("int");

                    b.Property<int>("RelationalOperator")
                        .HasColumnType("int");

                    b.Property<string>("SourceData_TradeExchange")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TimeInterval")
                        .HasColumnType("int");

                    b.Property<int>("TradeDirection")
                        .HasColumnType("int");

                    b.Property<string>("TradingPair_Domain")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ValueAsString")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("RecommendationFilterID");

                    b.ToTable("RecommendationFilter", "logic");
                });

            modelBuilder.Entity("TradingBots.Native.Domain.CompletedDeal", b =>
                {
                    b.HasBaseType("TradingBots.CrossCutters.Models.CompletedDealBase");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("TradingBots.CrossCutters.Models.CompletedDealBase", b =>
                {
                    b.OwnsOne("Alexis.CrossCutters.VersionInfo", "VersionInfo", b1 =>
                        {
                            b1.Property<string>("CompletedDealBaseCompletedDealID")
                                .HasColumnType("nvarchar(50)");

                            b1.Property<DateTime>("Created")
                                .HasColumnType("datetime2")
                                .HasColumnName("Created");

                            b1.Property<string>("PublishStatus")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("PublishStatus");

                            b1.Property<DateTime>("SystemCreated")
                                .HasColumnType("datetime2")
                                .HasColumnName("SystemCreated");

                            b1.Property<DateTime>("SystemUpdated")
                                .HasColumnType("datetime2")
                                .HasColumnName("SystemUpdated");

                            b1.Property<DateTime>("Updated")
                                .HasColumnType("datetime2")
                                .HasColumnName("Updated");

                            b1.Property<string>("UpdatedByUserID")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("UpdatedByUserID");

                            b1.HasKey("CompletedDealBaseCompletedDealID");

                            b1.ToTable("CompletedDeal", "logic");

                            b1.WithOwner()
                                .HasForeignKey("CompletedDealBaseCompletedDealID");
                        });

                    b.Navigation("VersionInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("TradingBots.Native.Domain.Bot", b =>
                {
                    b.HasOne("TradingBots.Native.Domain.Bot", null)
                        .WithOne()
                        .HasForeignKey("TradingBots.Native.Domain.Bot", "BotID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Alexis.CrossCutters.VersionInfo", "VersionInfo", b1 =>
                        {
                            b1.Property<string>("BotID")
                                .HasColumnType("nvarchar(50)");

                            b1.Property<DateTime>("Created")
                                .HasColumnType("datetime2")
                                .HasColumnName("Created");

                            b1.Property<string>("PublishStatus")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("PublishStatus");

                            b1.Property<DateTime>("SystemCreated")
                                .HasColumnType("datetime2")
                                .HasColumnName("SystemCreated");

                            b1.Property<DateTime>("SystemUpdated")
                                .HasColumnType("datetime2")
                                .HasColumnName("SystemUpdated");

                            b1.Property<DateTime>("Updated")
                                .HasColumnType("datetime2")
                                .HasColumnName("Updated");

                            b1.Property<string>("UpdatedByUserID")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("UpdatedByUserID");

                            b1.HasKey("BotID");

                            b1.ToTable("Bot_99_VersionInfo", "logic");

                            b1.WithOwner()
                                .HasForeignKey("BotID");
                        });

                    b.Navigation("VersionInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("TradingBots.Native.Domain.BotInstance", b =>
                {
                    b.HasOne("TradingBots.Native.Domain.Bot", null)
                        .WithMany("BotInstances")
                        .HasForeignKey("BotID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Alexis.CrossCutters.VersionInfo", "VersionInfo", b1 =>
                        {
                            b1.Property<string>("BotInstanceID")
                                .HasColumnType("nvarchar(50)");

                            b1.Property<DateTime>("Created")
                                .HasColumnType("datetime2")
                                .HasColumnName("Created");

                            b1.Property<string>("PublishStatus")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("PublishStatus");

                            b1.Property<DateTime>("SystemCreated")
                                .HasColumnType("datetime2")
                                .HasColumnName("SystemCreated");

                            b1.Property<DateTime>("SystemUpdated")
                                .HasColumnType("datetime2")
                                .HasColumnName("SystemUpdated");

                            b1.Property<DateTime>("Updated")
                                .HasColumnType("datetime2")
                                .HasColumnName("Updated");

                            b1.Property<string>("UpdatedByUserID")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("UpdatedByUserID");

                            b1.HasKey("BotInstanceID");

                            b1.ToTable("BotInstance", "logic");

                            b1.WithOwner()
                                .HasForeignKey("BotInstanceID");
                        });

                    b.Navigation("VersionInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("TradingBots.Native.Domain.BotInstanceState", b =>
                {
                    b.HasOne("TradingBots.Native.Domain.BotInstance", "BotInstance")
                        .WithOne("BotInstanceState")
                        .HasForeignKey("TradingBots.Native.Domain.BotInstanceState", "BotInstanceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Alexis.CrossCutters.VersionInfo", "VersionInfo", b1 =>
                        {
                            b1.Property<string>("BotInstanceStateID")
                                .HasColumnType("nvarchar(50)");

                            b1.Property<DateTime>("Created")
                                .HasColumnType("datetime2")
                                .HasColumnName("Created");

                            b1.Property<string>("PublishStatus")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("PublishStatus");

                            b1.Property<DateTime>("SystemCreated")
                                .HasColumnType("datetime2")
                                .HasColumnName("SystemCreated");

                            b1.Property<DateTime>("SystemUpdated")
                                .HasColumnType("datetime2")
                                .HasColumnName("SystemUpdated");

                            b1.Property<DateTime>("Updated")
                                .HasColumnType("datetime2")
                                .HasColumnName("Updated");

                            b1.Property<string>("UpdatedByUserID")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("UpdatedByUserID");

                            b1.HasKey("BotInstanceStateID");

                            b1.ToTable("BotInstanceState", "logic");

                            b1.WithOwner()
                                .HasForeignKey("BotInstanceStateID");
                        });

                    b.Navigation("BotInstance");

                    b.Navigation("VersionInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("TradingBots.Native.Domain.BotPartialTP", b =>
                {
                    b.HasOne("TradingBots.Native.Domain.BotInstance", null)
                        .WithMany("PartialTPs")
                        .HasForeignKey("BotInstanceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradingBots.Native.Domain.BotPartialTP", null)
                        .WithOne()
                        .HasForeignKey("TradingBots.Native.Domain.BotPartialTP", "BotPartialTPID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Alexis.CrossCutters.VersionInfo", "VersionInfo", b1 =>
                        {
                            b1.Property<string>("BotPartialTPID")
                                .HasColumnType("nvarchar(50)");

                            b1.Property<DateTime>("Created")
                                .HasColumnType("datetime2")
                                .HasColumnName("Created");

                            b1.Property<string>("PublishStatus")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("PublishStatus");

                            b1.Property<DateTime>("SystemCreated")
                                .HasColumnType("datetime2")
                                .HasColumnName("SystemCreated");

                            b1.Property<DateTime>("SystemUpdated")
                                .HasColumnType("datetime2")
                                .HasColumnName("SystemUpdated");

                            b1.Property<DateTime>("Updated")
                                .HasColumnType("datetime2")
                                .HasColumnName("Updated");

                            b1.Property<string>("UpdatedByUserID")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("UpdatedByUserID");

                            b1.HasKey("BotPartialTPID");

                            b1.ToTable("BotPartialTP_00_Root", "logic");

                            b1.WithOwner()
                                .HasForeignKey("BotPartialTPID");
                        });

                    b.Navigation("VersionInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("TradingBots.Native.Domain.GlobalStopLoss", b =>
                {
                    b.HasOne("TradingBots.Native.Domain.Bot", null)
                        .WithMany("GlobalStopLosses")
                        .HasForeignKey("BotID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Alexis.CrossCutters.VersionInfo", "VersionInfo", b1 =>
                        {
                            b1.Property<string>("GlobalStopLossID")
                                .HasColumnType("nvarchar(50)");

                            b1.Property<DateTime>("Created")
                                .HasColumnType("datetime2")
                                .HasColumnName("Created");

                            b1.Property<string>("PublishStatus")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("PublishStatus");

                            b1.Property<DateTime>("SystemCreated")
                                .HasColumnType("datetime2")
                                .HasColumnName("SystemCreated");

                            b1.Property<DateTime>("SystemUpdated")
                                .HasColumnType("datetime2")
                                .HasColumnName("SystemUpdated");

                            b1.Property<DateTime>("Updated")
                                .HasColumnType("datetime2")
                                .HasColumnName("Updated");

                            b1.Property<string>("UpdatedByUserID")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("UpdatedByUserID");

                            b1.HasKey("GlobalStopLossID");

                            b1.ToTable("GlobalStopLoss", "logic");

                            b1.WithOwner()
                                .HasForeignKey("GlobalStopLossID");
                        });

                    b.Navigation("VersionInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("TradingBots.Native.Domain.ReOrdersCategory", b =>
                {
                    b.OwnsOne("Alexis.CrossCutters.VersionInfo", "VersionInfo", b1 =>
                        {
                            b1.Property<string>("ReOrdersCategoryID")
                                .HasColumnType("nvarchar(50)");

                            b1.Property<DateTime>("Created")
                                .HasColumnType("datetime2")
                                .HasColumnName("Created");

                            b1.Property<string>("PublishStatus")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("PublishStatus");

                            b1.Property<DateTime>("SystemCreated")
                                .HasColumnType("datetime2")
                                .HasColumnName("SystemCreated");

                            b1.Property<DateTime>("SystemUpdated")
                                .HasColumnType("datetime2")
                                .HasColumnName("SystemUpdated");

                            b1.Property<DateTime>("Updated")
                                .HasColumnType("datetime2")
                                .HasColumnName("Updated");

                            b1.Property<string>("UpdatedByUserID")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("UpdatedByUserID");

                            b1.HasKey("ReOrdersCategoryID");

                            b1.ToTable("ReOrdersCategory", "logic");

                            b1.WithOwner()
                                .HasForeignKey("ReOrdersCategoryID");
                        });

                    b.Navigation("VersionInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("TradingBots.Native.Domain.ReOrdersMain", b =>
                {
                    b.OwnsOne("Alexis.CrossCutters.VersionInfo", "VersionInfo", b1 =>
                        {
                            b1.Property<string>("ReOrdersMainID")
                                .HasColumnType("nvarchar(50)");

                            b1.Property<DateTime>("Created")
                                .HasColumnType("datetime2")
                                .HasColumnName("Created");

                            b1.Property<string>("PublishStatus")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("PublishStatus");

                            b1.Property<DateTime>("SystemCreated")
                                .HasColumnType("datetime2")
                                .HasColumnName("SystemCreated");

                            b1.Property<DateTime>("SystemUpdated")
                                .HasColumnType("datetime2")
                                .HasColumnName("SystemUpdated");

                            b1.Property<DateTime>("Updated")
                                .HasColumnType("datetime2")
                                .HasColumnName("Updated");

                            b1.Property<string>("UpdatedByUserID")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("UpdatedByUserID");

                            b1.HasKey("ReOrdersMainID");

                            b1.ToTable("ReOrdersMain", "logic");

                            b1.WithOwner()
                                .HasForeignKey("ReOrdersMainID");
                        });

                    b.Navigation("VersionInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("TradingBots.Native.Domain.RecommendationAction", b =>
                {
                    b.OwnsOne("Alexis.CrossCutters.VersionInfo", "VersionInfo", b1 =>
                        {
                            b1.Property<string>("RecommendationActionID")
                                .HasColumnType("nvarchar(50)");

                            b1.Property<DateTime>("Created")
                                .HasColumnType("datetime2")
                                .HasColumnName("Created");

                            b1.Property<string>("PublishStatus")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("PublishStatus");

                            b1.Property<DateTime>("SystemCreated")
                                .HasColumnType("datetime2")
                                .HasColumnName("SystemCreated");

                            b1.Property<DateTime>("SystemUpdated")
                                .HasColumnType("datetime2")
                                .HasColumnName("SystemUpdated");

                            b1.Property<DateTime>("Updated")
                                .HasColumnType("datetime2")
                                .HasColumnName("Updated");

                            b1.Property<string>("UpdatedByUserID")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("UpdatedByUserID");

                            b1.HasKey("RecommendationActionID");

                            b1.ToTable("RecommendationAction", "logic");

                            b1.WithOwner()
                                .HasForeignKey("RecommendationActionID");
                        });

                    b.Navigation("VersionInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("TradingBots.Native.Domain.RecommendationFilter", b =>
                {
                    b.OwnsOne("Alexis.CrossCutters.VersionInfo", "VersionInfo", b1 =>
                        {
                            b1.Property<string>("RecommendationFilterID")
                                .HasColumnType("nvarchar(50)");

                            b1.Property<DateTime>("Created")
                                .HasColumnType("datetime2")
                                .HasColumnName("Created");

                            b1.Property<string>("PublishStatus")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("PublishStatus");

                            b1.Property<DateTime>("SystemCreated")
                                .HasColumnType("datetime2")
                                .HasColumnName("SystemCreated");

                            b1.Property<DateTime>("SystemUpdated")
                                .HasColumnType("datetime2")
                                .HasColumnName("SystemUpdated");

                            b1.Property<DateTime>("Updated")
                                .HasColumnType("datetime2")
                                .HasColumnName("Updated");

                            b1.Property<string>("UpdatedByUserID")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("UpdatedByUserID");

                            b1.HasKey("RecommendationFilterID");

                            b1.ToTable("RecommendationFilter", "logic");

                            b1.WithOwner()
                                .HasForeignKey("RecommendationFilterID");
                        });

                    b.Navigation("VersionInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("TradingBots.Native.Domain.Bot", b =>
                {
                    b.Navigation("BotInstances");

                    b.Navigation("GlobalStopLosses");
                });

            modelBuilder.Entity("TradingBots.Native.Domain.BotInstance", b =>
                {
                    b.Navigation("BotInstanceState")
                        .IsRequired();

                    b.Navigation("PartialTPs");
                });
#pragma warning restore 612, 618
        }
    }
}
