//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottron2000.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrawPayout
    {
        public int ItemID { get; set; }
        public string DrawPayoutID { get; set; }
        public string Division { get; set; }
        public Nullable<System.DateTime> PeriodStart { get; set; }
        public Nullable<System.DateTime> PerionEnd { get; set; }
        public Nullable<int> TotalDrawEvents { get; set; }
        public Nullable<int> TotalWinners { get; set; }
        public Nullable<int> TotalPayout { get; set; }
        public Nullable<int> AverageWinners { get; set; }
        public int AveragePayout { get; set; }
    }
}
