//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottron2000.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LottronEntities : DbContext
    {
        public LottronEntities()
            : base("name=LottronEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DrawPayout> DrawPayouts { get; set; }
        public DbSet<MockWinningPrize> MockWinningPrizes { get; set; }
        public DbSet<MockWinningPrizeShare> MockWinningPrizeShares { get; set; }
        public DbSet<PlayingSession> PlayingSessions { get; set; }
        public DbSet<ResultCheckSumSa> ResultCheckSumSas { get; set; }
        public DbSet<SALottoPlusResult> SALottoPlusResults { get; set; }
        public DbSet<SALottoPlusResultCheckSum> SALottoPlusResultCheckSums { get; set; }
        public DbSet<SALottoResult> SALottoResults { get; set; }
        public DbSet<SALottoResultCheckSum> SALottoResultCheckSums { get; set; }
        public DbSet<SATicketPrice> SATicketPrices { get; set; }
        public DbSet<SimulatedDraw> SimulatedDraws { get; set; }
        public DbSet<SimulatedDrawPrize> SimulatedDrawPrizes { get; set; }
        public DbSet<SimulatedDrawResult> SimulatedDrawResults { get; set; }
        public DbSet<SimulatedDrawTicket> SimulatedDrawTickets { get; set; }
        public DbSet<SimulatedDrawTicketResult> SimulatedDrawTicketResults { get; set; }
        public DbSet<SimulatedDrawWinningNumber> SimulatedDrawWinningNumbers { get; set; }
        public DbSet<WinningChance> WinningChances { get; set; }
        public DbSet<WinningNumberPermutation> WinningNumberPermutations { get; set; }
    }
}
