//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottron2000.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MockWinningPrize
    {
        public int ItemID { get; set; }
        public string MockWinningPrizeID { get; set; }
        public Nullable<int> SourceDrawNo { get; set; }
        public string DrawSubCategory { get; set; }
        public Nullable<int> Div1 { get; set; }
        public Nullable<int> Div2 { get; set; }
        public Nullable<int> Div3 { get; set; }
        public Nullable<int> Div4 { get; set; }
        public Nullable<int> Div5 { get; set; }
        public Nullable<int> Div6 { get; set; }
        public Nullable<int> Div7 { get; set; }
        public string CountryID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    }
}
