//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottron2000.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MockWinningPrizeShare
    {
        public int ItemID { get; set; }
        public string MockWinningPrizeShareID { get; set; }
        public Nullable<int> SourceDrawNo { get; set; }
        public string DrawSubCategory { get; set; }
        public Nullable<int> Div1Winners { get; set; }
        public Nullable<int> Div2Winners { get; set; }
        public Nullable<int> Div3Winners { get; set; }
        public Nullable<int> Div4Winners { get; set; }
        public Nullable<int> Div5Winners { get; set; }
        public Nullable<int> Div6Winners { get; set; }
        public Nullable<int> Div7Winners { get; set; }
        public string CountryID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    }
}
