//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottron2000.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayingSession
    {
        public PlayingSession()
        {
            this.SimulatedDraws = new HashSet<SimulatedDraw>();
        }
    
        public int ItemID { get; set; }
        public string PlayingSessionID { get; set; }
        public string SimulationType { get; set; }
        public string UserFriendlyReference { get; set; }
        public string Objectives { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string PublishStatus { get; set; }
    
        public virtual ICollection<SimulatedDraw> SimulatedDraws { get; set; }
    }
}
