//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottron2000.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultCheckSumSa
    {
        public ResultCheckSumSa()
        {
            this.SALottoPlusResultCheckSums = new HashSet<SALottoPlusResultCheckSum>();
            this.SALottoResultCheckSums = new HashSet<SALottoResultCheckSum>();
        }
    
        public int ItemID { get; set; }
        public string ResultCheckSumSaID { get; set; }
        public string DrawSubCategory { get; set; }
        public int CheckSum { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<decimal> OccuranceRatio { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> LastComputed { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    
        public virtual ICollection<SALottoPlusResultCheckSum> SALottoPlusResultCheckSums { get; set; }
        public virtual ICollection<SALottoResultCheckSum> SALottoResultCheckSums { get; set; }
    }
}
