//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottron2000.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALottoResultCheckSum
    {
        public int ItemID { get; set; }
        public string SALottoResultCheckSumID { get; set; }
        public string ResultCheckSumSaID { get; set; }
        public string SALottoResultID { get; set; }
    
        public virtual ResultCheckSumSa ResultCheckSumSa { get; set; }
        public virtual SALottoResult SALottoResult { get; set; }
    }
}
