//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottron2000.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALottoPlusResult
    {
        public SALottoPlusResult()
        {
            this.SALottoPlusResultCheckSums = new HashSet<SALottoPlusResultCheckSum>();
        }
    
        public Nullable<int> ItemID { get; set; }
        public string SALottoPlusResultID { get; set; }
        public int DrawNo { get; set; }
        public Nullable<System.DateTime> DrawDate { get; set; }
        public int Ball1 { get; set; }
        public int Ball2 { get; set; }
        public int Ball3 { get; set; }
        public int Ball4 { get; set; }
        public int Ball5 { get; set; }
        public int Ball6 { get; set; }
        public int BonusBall { get; set; }
        public Nullable<int> CheckSum { get; set; }
        public Nullable<int> Div1 { get; set; }
        public Nullable<int> Div2 { get; set; }
        public Nullable<int> Div3 { get; set; }
        public Nullable<int> Div4 { get; set; }
        public Nullable<int> Div5 { get; set; }
        public Nullable<int> Div6 { get; set; }
        public Nullable<int> Div7 { get; set; }
        public Nullable<int> Div1Winners { get; set; }
        public Nullable<int> Div2NoWinners { get; set; }
        public Nullable<int> Div3Winners { get; set; }
        public Nullable<int> Div4Winners { get; set; }
        public Nullable<int> Div5Winners { get; set; }
        public Nullable<int> Div6NoWinners { get; set; }
        public Nullable<int> Div7Winners { get; set; }
        public Nullable<int> PrizePayable { get; set; }
        public Nullable<int> Rollover { get; set; }
        public Nullable<int> RolloverCount { get; set; }
        public Nullable<int> NextEstimatedJackpot { get; set; }
        public Nullable<int> NextGuaranteedJackpot { get; set; }
        public Nullable<int> TotalSales { get; set; }
        public string DrawMachine { get; set; }
        public Nullable<int> BallSet { get; set; }
    
        public virtual ICollection<SALottoPlusResultCheckSum> SALottoPlusResultCheckSums { get; set; }
    }
}
