//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottron2000.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimulatedDrawTicketResult
    {
        public int ID { get; set; }
        public string SimulatedDrawTicketResultID { get; set; }
        public string SimulatedDrawTicketID { get; set; }
        public string DrawSubCategory { get; set; }
        public string WinningDivision { get; set; }
        public int NumberOfMatches { get; set; }
        public bool BonusMatch { get; set; }
        public bool IsJackpotWinner { get; set; }
        public int AmountWon { get; set; }
        public System.DateTime Created { get; set; }
    }
}
