//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottron2000.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimulatedDrawWinningNumber
    {
        public int ItemID { get; set; }
        public string SimulatedDrawWinningNumbersID { get; set; }
        public string SimulatedDrawID { get; set; }
        public string DrawSubCategory { get; set; }
        public Nullable<int> Num1 { get; set; }
        public Nullable<int> Num2 { get; set; }
        public Nullable<int> Num3 { get; set; }
        public Nullable<int> Num4 { get; set; }
        public Nullable<int> Num5 { get; set; }
        public Nullable<int> Num6 { get; set; }
        public Nullable<int> NumCheckSum { get; set; }
        public Nullable<int> Bonus { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    }
}
