//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottron2000.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimulatedDrawResult
    {
        public int ID { get; set; }
        public string SimulatedDrawResultID { get; set; }
        public string SimulatedDrawID { get; set; }
        public Nullable<int> AmountWon { get; set; }
        public Nullable<int> AmountLost { get; set; }
        public Nullable<int> AmountSpent { get; set; }
        public Nullable<int> Num1Matches { get; set; }
        public Nullable<int> Num2Matches { get; set; }
        public Nullable<int> Num3Matches { get; set; }
        public Nullable<int> Num4Matches { get; set; }
        public Nullable<int> Num5Matches { get; set; }
        public Nullable<int> Num6Matches { get; set; }
        public Nullable<int> BonusMatches { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    
        public virtual SimulatedDraw SimulatedDraw { get; set; }
    }
}
