//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottron2000.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimulatedDraw
    {
        public SimulatedDraw()
        {
            this.SimulatedDrawPrizes = new HashSet<SimulatedDrawPrize>();
            this.SimulatedDrawResults = new HashSet<SimulatedDrawResult>();
            this.SimulatedDrawTickets = new HashSet<SimulatedDrawTicket>();
        }
    
        public int ID { get; set; }
        public string SimulatedDrawID { get; set; }
        public string PlayingSessionID { get; set; }
        public string SimulationType { get; set; }
        public string WinningNumbersGenerationMethod { get; set; }
        public string PlayingNumbersGenerationMethod { get; set; }
        public string DrawPrizeGenerationMethod { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    
        public virtual PlayingSession PlayingSession { get; set; }
        public virtual ICollection<SimulatedDrawPrize> SimulatedDrawPrizes { get; set; }
        public virtual ICollection<SimulatedDrawResult> SimulatedDrawResults { get; set; }
        public virtual ICollection<SimulatedDrawTicket> SimulatedDrawTickets { get; set; }
    }
}
