//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottron2000.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimulatedDrawPrize
    {
        public int ItemID { get; set; }
        public string SimulatedDrawPrizeID { get; set; }
        public string SimulatedDrawID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string DrawSubCategory { get; set; }
        public Nullable<int> Div1 { get; set; }
        public Nullable<int> Div2 { get; set; }
        public Nullable<int> Div3 { get; set; }
        public Nullable<int> Div4 { get; set; }
        public Nullable<int> Div5 { get; set; }
        public Nullable<int> Div6 { get; set; }
        public Nullable<int> Div7 { get; set; }
        public Nullable<int> Div1Winners { get; set; }
        public Nullable<int> Div2Winners { get; set; }
        public Nullable<int> Div3Winners { get; set; }
        public Nullable<int> Div4Winners { get; set; }
        public Nullable<int> Div5Winners { get; set; }
        public Nullable<int> Div6Winners { get; set; }
        public Nullable<int> Div7Winners { get; set; }
    
        public virtual SimulatedDraw SimulatedDraw { get; set; }
    }
}
