//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottron2000.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WinningNumberPermutation
    {
        public int ID { get; set; }
        public Nullable<int> Number1 { get; set; }
        public Nullable<int> Number2 { get; set; }
        public Nullable<int> Number3 { get; set; }
        public Nullable<int> Number4 { get; set; }
        public Nullable<int> Number5 { get; set; }
        public Nullable<int> Number6 { get; set; }
        public Nullable<int> Bonus { get; set; }
        public Nullable<int> CheckSum { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    }
}
