//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lottron2000.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WinningChance
    {
        public int ItemID { get; set; }
        public string WinningChanceID { get; set; }
        public Nullable<int> PayoutOrder { get; set; }
        public string Division { get; set; }
        public Nullable<int> Odds { get; set; }
        public Nullable<decimal> Fraction { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public string DivisionDescription { get; set; }
    }
}
